"""
dashboard.py
------------
Streamlit dashboard for the E-Commerce Spark RDD project.
Reads the analytics CSV files generated by the Spark pipeline in data/output/
and displays an interactive UI.

Run with:
    streamlit run dashboard.py
"""

import os
import pandas as pd
import streamlit as st
import plotly.express as px

st.set_page_config(
    page_title="E-Commerce Sales Analytics",
    page_icon="🛍️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for polished aesthetics
st.markdown("""
<style>
    .kpi-card {
        background-color: #f8f9fa;
        border-radius: 8px;
        padding: 20px;
        text-align: center;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        border: 1px solid #e9ecef;
    }
    .kpi-value {
        font-size: 2.5em;
        font-weight: bold;
        color: #1f77b4;
    }
    .kpi-label {
        font-size: 1.1em;
        color: #6c757d;
        text-transform: uppercase;
        letter-spacing: 1px;
    }
    /* Dark mode support */
    @media (prefers-color-scheme: dark) {
        .kpi-card {
            background-color: #262730;
            border-color: #3b3d45;
        }
        .kpi-value { color: #4dabf7; }
        .kpi-label { color: #adb5bd; }
    }
</style>
""", unsafe_allow_html=True)


DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "output")

@st.cache_data
def load_data(filename: str) -> pd.DataFrame:
    path = os.path.join(DATA_DIR, filename)
    if os.path.exists(path):
        return pd.read_csv(path)
    return pd.DataFrame()

# -- Load Data -----------------------------------------------------------------
summary_df = load_data("summary_statistics.csv")
category_df = load_data("revenue_by_category.csv")
monthly_df = load_data("monthly_revenue.csv")
products_df = load_data("top_10_products.csv")
payment_df = load_data("payment_method_analysis.csv")
status_df = load_data("order_status_analysis.csv")
state_df = load_data("revenue_by_state.csv")

# -- Header --------------------------------------------------------------------
st.title("🛍️ E-Commerce Sales Analytics Dashboard")
st.markdown("Interactive dashboard powered by **Apache Spark RDD** pipeline outputs.")

if summary_df.empty:
    st.error("No data found! Please run the Spark pipeline first (`.\\run.ps1 pipeline`).")
    st.stop()

# -- KPIs ----------------------------------------------------------------------
# Extract KPIs from summary_statistics.csv
kpis = dict(zip(summary_df["metric"], summary_df["value"]))

# Use 5 columns for KPIs
col1, col2, col3, col4, col5 = st.columns(5)

def kpi_html(label, value):
    return f"""
    <div class="kpi-card">
        <div class="kpi-value">{value}</div>
        <div class="kpi-label">{label}</div>
    </div>
    """

with col1:
    val = kpis.get("Total Revenue ($)", 0)
    formatted_val = f"${float(val):,.0f}" if pd.notnull(val) else "$0"
    st.markdown(kpi_html("Total Revenue", formatted_val), unsafe_allow_html=True)
with col2:
    val = kpis.get("Total Transactions", 0)
    formatted_val = f"{int(val):,}" if pd.notnull(val) else "0"
    st.markdown(kpi_html("Transactions", formatted_val), unsafe_allow_html=True)
with col3:
    val = kpis.get("Average Order Value ($)", 0)
    formatted_val = f"${float(val):,.2f}" if pd.notnull(val) else "$0"
    st.markdown(kpi_html("Avg Order Value", formatted_val), unsafe_allow_html=True)
with col4:
    val = kpis.get("Unique Products", 0)
    formatted_val = f"{int(val):,}" if pd.notnull(val) else "0"
    st.markdown(kpi_html("Unique Products", formatted_val), unsafe_allow_html=True)
with col5:
    val = kpis.get("Unique Customers", 0)
    formatted_val = f"{int(val):,}" if pd.notnull(val) else "0"
    st.markdown(kpi_html("Unique Customers", formatted_val), unsafe_allow_html=True)

st.markdown("<br>", unsafe_allow_html=True)

# -- Charts --------------------------------------------------------------------
row1_col1, row1_col2 = st.columns(2)

with row1_col1:
    st.subheader("Revenue by Category")
    if not category_df.empty:
        # Sort descending
        cat_sorted = category_df.sort_values(by="total_revenue", ascending=True)
        fig_cat = px.bar(
            cat_sorted, 
            x="total_revenue", 
            y="category", 
            orientation="h",
            color="total_revenue",
            color_continuous_scale="Blues",
            labels={"total_revenue": "Revenue ($)", "category": "Category"},
            title="Total Revenue per Product Category"
        )
        fig_cat.update_layout(coloraxis_showscale=False)
        st.plotly_chart(fig_cat, use_container_width=True)

with row1_col2:
    st.subheader("Monthly Revenue Trend")
    if not monthly_df.empty:
        fig_month = px.area(
            monthly_df, 
            x="year_month", 
            y="total_revenue",
            markers=True,
            labels={"total_revenue": "Revenue ($)", "year_month": "Month"},
            title="Revenue Trend over Time"
        )
        fig_month.update_traces(line_color="#1f77b4", fillcolor="rgba(31, 119, 180, 0.3)")
        st.plotly_chart(fig_month, use_container_width=True)


row2_col1, row2_col2 = st.columns(2)

with row2_col1:
    st.subheader("Top 10 Products by Revenue")
    if not products_df.empty:
        prod_sorted = products_df.sort_values(by="total_revenue", ascending=True)
        fig_prod = px.bar(
            prod_sorted, 
            x="total_revenue", 
            y="product_name", 
            orientation="h",
            color="total_revenue",
            color_continuous_scale="Teal",
            labels={"total_revenue": "Revenue ($)", "product_name": "Product"},
            title="Best Selling Products"
        )
        fig_prod.update_layout(coloraxis_showscale=False)
        st.plotly_chart(fig_prod, use_container_width=True)

with row2_col2:
    st.subheader("Revenue by Payment Method")
    if not payment_df.empty:
        fig_pay = px.pie(
            payment_df, 
            values="total_revenue", 
            names="payment_method",
            hole=0.4,
            title="Revenue Contribution by Payment Type",
            color_discrete_sequence=px.colors.qualitative.Set3
        )
        st.plotly_chart(fig_pay, use_container_width=True)


row3_col1, row3_col2 = st.columns(2)

with row3_col1:
    st.subheader("Order Status Distribution")
    if not status_df.empty:
        fig_status = px.bar(
            status_df, 
            x="order_status", 
            y="transaction_count",
            color="order_status",
            labels={"transaction_count": "Number of Orders", "order_status": "Status"},
            title="Transaction Volume by Status"
        )
        fig_status.update_layout(showlegend=False)
        st.plotly_chart(fig_status, use_container_width=True)

with row3_col2:
    st.subheader("Revenue by State (Top 15)")
    if not state_df.empty:
        state_sorted = state_df.sort_values(by="total_revenue", ascending=False).head(15)
        # Sort back to ascending for horizontal bar chart
        state_sorted = state_sorted.sort_values(by="total_revenue", ascending=True)
        fig_state = px.bar(
            state_sorted, 
            x="total_revenue", 
            y="state", 
            orientation="h",
            color="total_revenue",
            color_continuous_scale="Purp",
            labels={"total_revenue": "Revenue ($)", "state": "State"},
            title="Top 15 States by Revenue"
        )
        fig_state.update_layout(coloraxis_showscale=False)
        st.plotly_chart(fig_state, use_container_width=True)

# Footer
st.markdown("---")
st.markdown("*Data processed and cleaned using Apache Spark RDDs.*")
